# Generated by Django 4.2.6 on 2023-11-02 02:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.TextField(blank=None, default='default_picture.png', max_length=250, null=None)),
                ('nickname', models.TextField(blank=None, max_length=50, null=None, unique=True)),
                ('password', models.TextField(blank=None, max_length=250, null=None)),
                ('firstname', models.TextField(blank=None, max_length=250, null=None)),
                ('lastname', models.TextField(max_length=250)),
                ('biography', models.TextField(max_length=250)),
                ('email', models.EmailField(blank=None, max_length=250, null=None)),
                ('commit', models.DateTimeField(blank=None, default=datetime.datetime.now, null=None)),
                ('modified', models.DateTimeField()),
                ('status', models.IntegerField(blank=None, default=1, max_length=1, null=None)),
            ],
        ),
    ]
