# Generated by Django 4.2.6 on 2023-11-02 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='modified',
            field=models.DateTimeField(null=True),
        ),
    ]
