# Generated by Django 4.2.6 on 2023-11-02 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodblog', '0002_alter_user_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.IntegerField(blank=None, default=1, null=None),
        ),
    ]
